[[constraint]]
  name = "github.com/fluent/fluent-logger-golang"
  version = "1.2.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true
